# Generated by Django 5.0.4 on 2024-05-05 21:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Ingredient",
            fields=[
                ("ingredient_id", models.AutoField(primary_key=True, serialize=False)),
                ("ingredient_name", models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name="Recipe",
            fields=[
                ("recipe_id", models.AutoField(primary_key=True, serialize=False)),
                ("recipe_name", models.CharField(max_length=200)),
                ("recipe_rating", models.IntegerField()),
                ("recipe_description", models.CharField(max_length=1000)),
                ("recipe_comments", models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name="Formula",
            fields=[
                ("recipe_type_id", models.AutoField(primary_key=True, serialize=False)),
                ("recipe_type_name", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="IngredientType",
            fields=[
                ("ing_type_id", models.AutoField(primary_key=True, serialize=False)),
                ("ing_type_name", models.CharField(max_length=200)),
                (
                    "ingredient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="recipes.ingredient",
                    ),
                ),
                (
                    "recipe_type_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="recipes.Formula",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="RecipeIngredients",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "ingredient_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="recipes.ingredient",
                    ),
                ),
                (
                    "recipe_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="recipes.recipe"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="RecipeRequirement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("required", models.BooleanField()),
                (
                    "ing_type_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="recipes.ingredienttype",
                    ),
                ),
                (
                    "recipe_type_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="recipes.Formula",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="recipe",
            name="recipe_type_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="recipes.Formula"
            ),
        ),
    ]
