# Generated by Django 5.1 on 2025-07-20 18:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("recipes", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="ingredienttype",
            old_name="recipe_type_id",
            new_name="formula",
        ),
    ]
