# Generated by Django 5.0.4 on 2024-05-05 21:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("recipes", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="RecipeIngredients",
            new_name="RecipeIngredient",
        ),
    ]
