# Generated by Django 5.1 on 2026-02-13 03:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("recipes", "0002_rename_recipe_type_id_ingredienttype_formula"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="recipe",
            name="recipe_comments",
        ),
        migrations.RemoveField(
            model_name="recipe",
            name="recipe_description",
        ),
        migrations.RemoveField(
            model_name="recipe",
            name="recipe_rating",
        ),
    ]
