# Generated by Django 5.1 on 2024-08-30 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recipes", "0003_remove_ingredienttype_ingredient_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ingredienttype",
            name="ing_type_multiple",
            field=models.BooleanField(
                default=True, verbose_name="Multiple of this Ingredient Allowed?"
            ),
        ),
        migrations.AlterField(
            model_name="ingredienttype",
            name="ing_type_required",
            field=models.BooleanField(
                default=False, verbose_name="Required by Formula?"
            ),
        ),
    ]
